name: hackathon_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #navigation
  auto_route: ^3.2.2

  #service locator
  get_it: ^7.2.0

  #tools
  equatable: ^2.0.3
  flutter_dotenv: ^5.0.2
  dart_jsonwebtoken: ^2.4.0  
  #network
  dio: ^4.0.4

  #state management
  flutter_bloc: ^8.0.1

  #firebase_auth_rest
  firebase_auth_rest:
    path: modules/firebase_auth_rest

  #firebase_db_rest
  firebase_db_rest:
    path: modules/firebase_db_rest

  #localDb
  hive_flutter: ^1.1.0

  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #code generators
  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1

  flutter_lints: ^1.0.0


flutter:
  
  
  assets:
 
    - .env
  uses-material-design: true

